### ISSUE TITLE
do your releases work in Linux as well?

### ISSUE THREAD

**Issue by sido420** [slee047/node-packer#1]
I was having trouble running them on Linux last time I tried.

**Comment by slee047** [comment]
Hi there, it is coincidence that I need to get this to work in Linux as well. So now I have tested that these releases (Node.js 10 - Recommended by Node.js: 1.6.0-10.13.0-1, Node.js 8: 1.6.0-8.12.0-1) works in both Windows and Ubuntu 18.04 LTS.

A StarterKit branch is also created as a way to test if the nodec can compile Node.js web application as expected or not. This would help to raise feedback when bug arises.

Thank you for your support to nodec.
