### ISSUE TITLE
Support for XCode 11?

### ISSUE THREAD

**Issue by iWinston** [slee047/node-packer#14]
XCode 11 has come.  It fails when the build environment is XCode 11 now. 

![image](https://user-images.githubusercontent.com/23229557/65389221-44bb6a00-dd86-11e9-97f0-bb44e28d8c12.png)

**Comment by slee047** [comment]
I saw 2 issues:

1) You have only installed Node.js 8.12.0 **or** that Node.js 10.6.0 is not the default Node.js version in your system.

2) You need to update Openssl to a much newer version. 

3) Try to install NASM (http://macappstore.org/nasm/)


If all these you have tried (You should not get the === WARNING === message at the minimum), and still fails to build, then I suspect that the code does not support XCode 11.

I have failure in Travis CI before.

**Comment by iWinston** [comment]
I have done all the things you mentioned.  But the problem still exists. 
![image](https://user-images.githubusercontent.com/23229557/65406659-cbb62400-de12-11e9-8df4-b67685e10c4e.png)
NASM is needed only on Windows. And I think it is something wrong when building Node.js with Xcode11 (https://github.com/nodejs/node/blob/v10.0.0/BUILDING.md#openssl-asm-support). Maybe I should downgrade Xcode to 10.x.

**Comment by slee047** [comment]
> I have done all the things you mentioned. But the problem still exists.
> 
> ![image](https://user-images.githubusercontent.com/23229557/65406659-cbb62400-de12-11e9-8df4-b67685e10c4e.png)
> 
> I think there's something wrong when building Node.js with Xcode11 (https://github.com/nodejs/node/blob/v10.0.0/BUILDING.md#openssl-asm-support). Maybe I should downgrade Xcode to 10.x.

I have similar issue before, and that was during XCode 11 in beta stages. But LibreSSL? Try using OpenSSL from Brew instead (https://formulae.brew.sh/formula/openssl)?

**Comment by iWinston** [comment]
![image](https://user-images.githubusercontent.com/23229557/65408985-366a5e00-de19-11e9-9f1e-d15d0533ed13.png)
Sorry, I forgot to set OpenSSL to my PATH. But there's still the same error.

**Comment by iWinston** [comment]
`
    # supported asm compiler for AVX2. See https://github.com/openssl/openssl/
    # blob/OpenSSL_1_1_0-stable/crypto/modes/asm/aesni-gcm-x86_64.pl#L52-L69
    openssl110_asm_supported = \
      ('gas_version' in variables and float(variables['gas_version']) >= 2.23) or \
      ('xcode_version' in variables and float(variables['xcode_version']) >= 5.0) or \
      ('llvm_version' in variables and float(variables['llvm_version']) >= 3.3) or \
      ('nasm_version' in variables and float(variables['nasm_version']) >= 2.10)
    if is_x86 and not openssl110_asm_supported:
      error('''Did not find a new enough assembler, install one or build with
       --openssl-no-asm.
       Please refer to BUILDING.md''')
`
I ran [./configure] and found the values of `variables['xcode_version'])`  and `variables['llvm_version']`  were both equal  to 0.

**Comment by iWinston** [comment]
It costs almost 1 hour to pack on  Node.js 10.16.0. But it can support Xcode11 just after the patch, Thank you.@slee047
