### ISSUE TITLE
Can't find the NASM.exe. 

### ISSUE THREAD

**Issue by YYago** [slee047/node-packer#2]
When the NASM installed for the current user of computer, It can't find `nasm.exe` after run the command.

- OS: Windows 10 x64

The `NASM v2.14`  default install to `C:/user/[username]/AppData/Local/bin/NASM/` .  Only when installed as Administrator will install to "%ProgramFiles%\..."  or  "%ProgramFile(x86)%\..." .

Can It works, if only install for the single user of PC?  If it works normal,  We can add the path:`'C:/user/[username]/AppData/Local/bin/NASM/'`  to the file [node/tools/msvs/find_nasm.cmd](https://github.com/slee047/node-packer/blob/Series10/node/tools/msvs/find_nasm.cmd).

yes, I have solved this error. When I reinstall the NASM to 'C:/ProgramFiles/....' as Admin after uninstall it.

In fact, That is a trouble. It's hard to guess where the user will install the NASM.  Just asks users to add the path of the NASM installed to the system environment variables('PATH'). 

*At first, I never knew that I needed to install the `nasm.exe` .Of course, It's my problem.*

----Wow, Translated with AI.

**Comment by slee047** [comment]
Glad that you have found a fix to the problem :)
